#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

duration=5
opts=$(getopt -q -o "" --longoptions "duration:" -n "getopt.sh" -- "$@")
eval set -- "$opts"
while true; do
    case "$1" in
        --duration)
            shift
            duration=$1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            ;;
    esac
done

# Rickshaw adds its own flat padding (RUNTIME_PADDING, 180s) on top of
# whatever this echoes before using it as the roadblock timeout, so no
# additional margin is added here -- matching bench-uperf/bench-fio,
# which also echo the raw duration unmodified.
echo $duration
